# Generated by Django 6.0.3 on 2026-03-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_founditem_image_lostitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostitem',
            name='reward',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='item_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='location_found',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='item_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='location_lost',
            field=models.CharField(max_length=200),
        ),
    ]
