# Generated by Codex on 2026-03-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_contactmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="founditem",
            name="found_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="founditem",
            name="handover_location",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="founditem",
            name="matched_lost_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matched_found_reports",
                to="main.lostitem",
            ),
        ),
    ]
