# Generated by Django 6.0.3 on 2026-03-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_lostitem_reward_alter_founditem_item_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitem',
            name='reward',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
